_target_: pytorch_lightning.Trainer

min_epochs: 1000
max_epochs: 1000
check_val_every_n_epoch: 50

accelerator: cpu
devices: 1

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
