_target_: src.models.parallel_energy_gfn_module.PerNodeParallelLinearTrainableCausalGraphGFlowNetModule

env_batch_size: 64
eval_batch_size: 100
full_posterior_eval: False
uniform_backwards: True
debug_use_shd_energy: False
analytic_use_simple_mse_energy: True
loss_fn: "detailed_balance"
alpha: 0
temperature: 0.01
temper_period: 5
prior_lambda: 100
beta: 0.01
confidence: 0.0
hidden_dim: 128
gfn_freq: 1
energy_freq: 1
pretraining_epochs: 0
lr: 1e-4
hyper: "mlp"
bias: True
